[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[global]
developmentMode = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"


